### ISSUE TITLE
Could the schema execution be made even more async by adding an async executor

### ISSUE THREAD

**Issue by japrogramer** [datadvance/DjangoChannelsGraphqlWs#1]
https://github.com/datadvance/DjangoChannelsGraphqlWs/blob/bb043d4eae97723df323c46f67ffb904e475a3e0/channels_graphql_ws/graphql_ws.py#L532

`executor=AsyncioExecutor(loop=asyncio.get_event_loop()),`

if this line is changed to include the above as a parameter, does it raise this same issue
https://github.com/graphql-python/graphene-django/issues/452

Really appreciate you sharing your code, I intend to migrate over to this implementation after i do some testing

**Comment by japrogramer** [comment]
@prokher one of the reason's I would like and currently have my own implementation to have an async executor is that I would like to make async calls to aioredis. Im not to experienced to know what the difference it would make to run in the main thread than to  offloading to a separate thread in terms of scalability which is my main concern.

**Comment by prokher** [comment]
@japrogramer I've made the following. Now (since aaa523269513a201289b03afc12cfe08f9a2898d) server processes requests (WebSocket messages) in parallel in different worker threads and `AsyncioExecutor` is used inside these worker threads. This allows to implement `async` resolvers and at the same time protects from locking the main eventloop where networking happens.

In spite of query and mutation resolvers seem to work fine, I indeed faced an issue with subscriptions. It looks very similar to the issue you posted to the `graphql-core` https://github.com/graphql-python/graphql-core/issues/149 .

Now I need to think about a workaround. I always have an option to execute subscription "resolvers" ( `subscribe` and `publish`) in a worker thread with its own eventloop. This will have negative influence on performance, but will allow users to use `async` resolvers for subscriptions as well. And once `graphql-core` issue is fixed, this kluge can easily be removed. I am still not sure it is a proper way to.

**Comment by japrogramer** [comment]
@prokher I think the issue is more closely related to this https://github.com/graphql-python/graphene-django/issues/452

**Comment by japrogramer** [comment]
I think this is the piece of code that may be preventing async subscription resolvers to execute as expected.
https://github.com/graphql-python/graphql-core/pull/102#discussion_r194278144

**Comment by prokher** [comment]
It seems that finally (in v0.1.18) all "resolver" methods (such as `subscribe`, `publish`, `unsubscribed`) can be implemented as both synchronous and asynchronous functions. So I am closing this. Reopen if it is not.

**Comment by japrogramer** [comment]
do you mean RxPy now allows async resolves .. or graphene resolver can be async?
if it's the latter yes, i believe i tried that.

Im looking into https://github.com/strawberry-graphql/strawberry

**Comment by prokher** [comment]
@japrogramer Yes, I meant that "resolvers" of the Query, Mutation & Subscription classes can be implemented as `async def` methods. Actually, since v0.1.18 it is possible to implement all Subscription methods as `async def`.

Indeed, [strawberry](https://github.com/strawberry-graphql/strawberry) looks interesting. Taking into account the appearance of [graphql-core-next](https://github.com/graphql-python/graphql-core-next) and the progress of [tartiflette](https://github.com/dailymotion/tartiflette) (which seems to develop quite intensively these days), I will probably have to consider adding a replaceable "GraphQL-processing" layer to the current implementation. I am not sure, though.
