### ISSUE TITLE
Support middlewares

### ISSUE THREAD

**Issue by hvdklauw** [datadvance/DjangoChannelsGraphqlWs#15]
Currently you can't use middlewares

For instance the `graphene_django.debug.DjangoDebugMiddleware` would be useful to be able to use to debug the queries.

I get the `GRAPHENE` setting from graphene-django isn't used and it calls it's own `graphql.graphql` which is where the middlewares should be passed. 
So maybe just make it an attribute of the `GraphqlWsConsumer` and pass it along?

**Comment by prokher** [comment]
Dear @hvdklauw,

I am not 100% sure, but I suppose, the middlewares you are mentioning are designed to work with HTTP requests and responses. Indeed `DjangoChannelsGraphqlWs` does not use them, since here all the traffic (queries, mutations & subscriptions) goes through the WebSocket. Probably we can develop some mechanism to inject middlewares into the WebSocket message processing pipeline. But I afraid this will not allow injecting HTTP middlewares anyway.

Meanwhile, I suppose you still can use Graphene's `GraphQLView` and route queries & mutations to HTTP, so middlewares you need will work. Here is [the relevant part of the Graphene Django tutorial](http://docs.graphene-python.org/projects/django/en/latest/tutorial-plain/#creating-graphql-and-graphiql-views).

**Comment by hvdklauw** [comment]
No, I'm not talking about http middlewares, but about [graphene middleware](https://docs.graphene-python.org/en/latest/execution/middleware/)

it has nothing to do with http, and everything with resolvers.

**Comment by prokher** [comment]
@hvdklauw I get your point. Adding class field `middleware` to the `GraphqlWsConsumer` seems reasonable and quite easy. Thank you, we will take a look.

**Comment by hvdklauw** [comment]
Ok, I looked into this and it's a bit harder then I thought. Just passing in the middlewares isn't enough (they don't get called).

I tried to figure out where middlewares are executed but I couldn't figure it out.

**Comment by prokher** [comment]
Middleware support adde in v0.3.0. Please take a look at the updated example. Closing this. Feel free to reopen is something goes wrong.
