### ISSUE TITLE
Publish method never called

### ISSUE THREAD

**Issue by chiubaka** [datadvance/DjangoChannelsGraphqlWs#30]
Hi, newly experimenting with this library. Thanks for creating it :)--it seems there aren't a lot of great alternatives out there for this specific use case.

Currently, I'm having trouble getting my messages to publish and get sent down to the client... with logging, I've verified that my subscribe and broadcast methods work as expected... but I never see a `publish` printed to the log, and I never receive data sent over the web socket on my client.

In case this context is important, I'm currently running Channels with an in memory channel layer (while I play with this library--I'll migrate to Redis later), and my broadcast actions are being triggered by a management command script running separately from the server itself.

Am I just missing something silly here?

```
class OnNewNotification(channels_graphql_ws.Subscription):
    notification = String()

    @staticmethod
    def subscribe(root, info):
        user = info.context.user
        print("OnNewNotification#subscribe")
        if user is not None:
            print(user)
            print(user.is_anonymous)
            print(user.id)
        else:
            "No user"
        # return [str(user.id)] if user is not None and not user.is_anonymous else None
        return ["test"]

    @staticmethod
    def publish(payload, info):
        print("OnNewNotification#publish")
        return OnNewNotification(notification="Test message")

    @classmethod
    def new_notification(cls, notification):
        print("OnNewNotification.new_notification")
        print(notification.recipient.id)
        cls.broadcast(
            # group=str(notification.recipient.id),
            group="test",
            payload="Test message"
        )
```

**Comment by ThomasCorblin** [comment]
Hello,

Did you find a solution? I have the same issue, publish and subscribe are never called.

Thanks 
T.

**Comment by chiubaka** [comment]
I haven't found a solution to my problem yet, but in my case `subscribe` is definitely called though `publish` is not, so I don't think we're experiencing the same thing. I'd venture to guess that something of yours is misconfigured.

**Comment by felipeacunago** [comment]
Hi, I tried upgrading from django 2.0.13 (where it was working without any issues) to django 2.2.9, and this is happening to me now.

If I return the environment to 2.0.13 it works though.

What django version do you have?

**Comment by felipeacunago** [comment]
Hi, this started happening to me when I upgraded django from 2.0.13 to 2.2.9.

Which django version are you using?

**Comment by chiubaka** [comment]
My Pipfile shows a Django version of 2.2.8. Just saw a message in my inbox that didn't appear in this thread suggesting a similar problem but where this was working with Django 2.0.13 and not in 2.2.9.

**Comment by felipeacunago** [comment]
> My Pipfile shows a Django version of 2.2.8. Just saw a message in my inbox that didn't appear in this thread suggesting a similar problem but where this was working with Django 2.0.13 and not in 2.2.9.

Yeah sorry it was me. For me it was working until I upgraded django, but I'm noticing it's a different issue, as the subscription is not working (it gets called but it fails) because I'm getting an error on Rx (version 3.0.1) telling me it doesn't have subjects.

When using:

Django==2.0.13
django-channels-graphql-ws==0.2.0
Rx==1.6.1

it worked flawlessly.

Using the example with this setup throws an error when using subscriptions:

Django==2.2.9
django-channels-graphql-ws==0.4.2
Rx==3.0.1

![image](https://user-images.githubusercontent.com/44075111/71704139-43eb9880-2db7-11ea-96aa-ed8a7e4beba2.png)

Were you able to fix it?

**Comment by prokher** [comment]
As far as I understood, the problem was caused by the incompatible `rx` library, isn't it? `DjangoChannelsGraphqlWs` does not depend on `rx` directly but through a chain of modules. As far as I see it depends on `rx` through the `graphql-core` which is hold on `2.3.1` by `graphene`. 

In other words. The problems is that there is `rx` of version `3` in the Python where `DjangoChannelsGraphqlWs` installed. `DjangoChannelsGraphqlWs` dependencies will lead (indirectly) to the `rx` of version `1.6.1`, so you clearly installed `rx 3` using some crafty hacks. 

So, if you just install like `README.md` recommends `pip install django-channels-graphql-ws` then it should work. Anyway, there is nothing I can do with this. The problem is that `graphql-core 2.3.1` depends on `rx 1.6.1`, and it is hold by the latest stable `graphene` `DjangoChannelsGraphqlWs ` depends on. I suppose we should wait until `graphene` `3` releases and then update.
