### ISSUE TITLE
Django 3 support

### ISSUE THREAD

**Issue by hvdklauw** [datadvance/DjangoChannelsGraphqlWs#35]
Hey,

I tried upgrading to django 3.0 but poetry complained right away that it was not possible because this package does not support django 3.0.

So, what is needed to get it working with django 3.0?

**Comment by prokher** [comment]
@hvdklauw Hm. We need to take a look at this. We have not tried to used it with new Django. Probably it is the time to start trying.

**Comment by tony** [comment]
@prokher Do you think we need to relax the django version restriction here? https://github.com/datadvance/DjangoChannelsGraphqlWs/blob/master/pyproject.toml#L54

**Comment by tony** [comment]
@prokher I added a PR at #37 to fix travis / loosen version dependencies.

**Comment by prokher** [comment]
@tony Thank you very much, we have a bunch of open issues here, so I suppose it is the time to initiate a designated sprint for this project. I will definitely review and merge your PR. Stay tuned, hope this will happen in a couple of weeks. Hope this is not that critical for you at the moment. Thanks again.

**Comment by tony** [comment]
@prokher Thanks for your response. This fixes a block many have moving to django 3.0. It should be a packaging issue only, hopefully!

I think this is _could_ be okay to do a "quick merge" and release on - since it's just adjusting packaging and releasing to pypi. *I think* - that is. I don't have much poetry experience yet!

**Comment by tony** [comment]
@hvdklauw @prokher I went back to the PR at #37 and relaxed some the changes, fixed travis, and linting.  This removes the cap on Django 2.x  and allows 3.x releases, as well as reduces the python interpreter minimum version to 3.6 (from 3.7)

Even graphql-core-next will only need python 3.6: https://github.com/graphql-python/graphql-core-next

**Comment by prokher** [comment]
The version 0.5.0 is here. I've relaxes Poetry dependencies so now it should not conflict with Django 3. I have not tested it thoroughly yet though, since I not migrated projects which use DjangoChannelsGraphqlWs to Django 3 yet. Anyway, all tests pass, and example seems to work fine with Django 3. So I am closing this. Please feel free to reopen of submit new issues if there are any problems. Cheers.
