### ISSUE TITLE
can not serialize 'datetime.datetime' object

### ISSUE THREAD

**Issue by Suor** [datadvance/DjangoChannelsGraphqlWs#43]
Is there a way to serialize datetime or a way to substitute serializer?

**Comment by Suor** [comment]
This happens when I try to broadcast some dicts containing datetimes.

**Comment by prokher** [comment]
Dear @Suor, thank you for reporting this. I will take a look. I am not sure whether I should simply add support for types `datetime.date` and `datetime.datetime` or add a way to provide custom serializers. The former seems to be easier to implement, so I tend to just supporting these types directly in the code. I realize that providing mechanism to customize serialization is more generic, but since nobody has asked for this I would like to preserve the effort for something else.

**Comment by prokher** [comment]
Implemented this in [v0.7.0](https://github.com/datadvance/DjangoChannelsGraphqlWs/releases/tag/v0.7.0).
